# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDlfYNYrUXkS6y52Cdju3ZpflnR9ER3Y
"""

import matplotlib.pyplot as plt
hours = [1, 2, 3,4 ,5,  6, 7, 8]
visitors = [50, 60, 65, 70, 90, 120, 110, 130]

plt.plot(hours,visitors,
         color ="green",
         marker="s",
         linestyle = "--",
         linewidth=2,
         alpha=1,
         label="visitors")
plt.title("website visitors per Hour")
plt.xlabel("hour of day")
plt.ylabel("number of visitors")
plt.legend()

plt.grid(True,linestyle="-",alpha=1)
plt.show()

Simport matplotlib.pyplot as plt

products = ["laptop","Mobile","Tablet","Headphones","Smartwatch"]
sales = [250, 400, 150, 300, 180]

plt.bar(products,sales,color ="skyblue",edgecolor="black",alpha =1,width =0.5)
plt.title("Product sale Comparision")
plt.xlabel("Products")
plt.ylabel("Units sold")
plt.show()

import matplotlib.pyplot as plt

marks = [45, 55, 60,72,68,80,55,67,70,
         85,77, 65, 90,78,45,87,89,78,
         45,67,89,41,54,65,76,87,98,54]


plt.hist(marks, bins= 10, histtype ="bar",color= "green",edgecolor="black",density=True)
plt.title("Distribution of students")
plt.xlabel("Marks Range")
plt.ylabel("number of students")
plt.show()

import matplotlib.pyplot as plt
brands =["apple","samsung","appo","oneplus","others"]
market_share =[30,25,10,20,15]
plt.pie(market_share,
        labels=brands,
        autopct ="%.2f%%",
        startangle =90,
        colors =["gold","red","pink","skyblue","yellow"],
        explode = [0,0,0,0.1,0],
        shadow =True)
plt.title("Mobile Market Share 2025")
plt.show()

from matplotlib import colorbar
#scatterplot
import matplotlib.pyplot as plt

ad_spend =[2, 4, 5, 7, 8, 10,11,12]
sales =[27, 25, 28, 35, 40, 48, 50, 52]
profit =[200, 250, 90, 350, 40, 80, 500, 520]

plt.scatter(ad_spend,sales,
            s =profit,
            c=profit,
            cmap="Reds",
            alpha =0.8,
            edgecolor="black",
            linewidth=1.3)
plt.title("Advertising Spends vs Sales(with color & size)",fontsize=14,fontweight="bold")
plt.xlabel("Ad Spend($1000s)",fontsize=12)
plt.ylabel("sales($1000s)",fontsize=12)

plt.colorbar(label="Sales Values")
plt.grid(True, linestyle="--",alpha=0.2)
plt.show()

import matplotlib.pyplot as plt
scores = [
    [70, 68, 86, 78, 89, 66, 69, 9],
    [65, 70, 68, 72, 75, 78, 79, 66],
    [89, 98, 87, 88, 83, 85, 84, 80],
    [60, 61, 62, 63, 64, 65, 66,90],
    [79, 86, 98, 67, 90, 56, 8, 78]]
plt.boxplot(scores,
            patch_artist=True,
            medianprops=dict(color="red",linewidth=1),
            whiskerprops=dict(color="green",linewidth=1),
            capprops=dict(color="black",linewidth=1),
            notch=True,
            vert=True,
            labels=["A","B","C","D","E"])
plt.grid(True, linestyle="--",alpha=1)
plt.title("exams scores distribution across classes")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

data = np.array([
    [30,32,31,29,28,27,26],
    [33,34,32,30,29,28,27],
    [35,36,37,34,33,29,20],
    [37,38,39,32,28,29,37],
    [36,37,28,29,38,39,33]

])

days = ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"]
weeks = ["Week1", "Week2", "Week3", "Week4", "Week5"]

sns.heatmap(data,
            annot = True,
            fmt=".2f",
            cmap="YlOrRd",
            linewidth = 0.5,
            xticklabels = days,
            yticklabels = weeks

            )
plt.title("Weekly Temperature Heatmap", fontsize=14,fontweight = "bold")
plt.xlabel = ("Days of the week")
plt.ylabel = ("Weeks")
plt.show()