# -*- coding: utf-8 -*-
"""Webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyHXXWqCR24LWGKAJYg0pWL4Bxrl7CPl
"""

#Loading requried libraries
import requests
from bs4 import BeautifulSoup

URL ='https://codegnan.com/'

# Loading the webpage in memory usinhg requests library
page = requests.get(URL)



# check the status coge of page
page.status_code

htmlCode = page.text
print(type(htmlCode))

soup = BeautifulSoup(htmlCode,'html.parser')
print(soup)

title = soup.title.text
print("Website Title:",title)

headings = soup.find_all('h2')
for heading in headings:
  print(heading.text.strip())

links = soup.find_all("a")
for link in links:
  print(link.get("href"))

images = soup.find_all("img")
for image in images:
  print(image.get('src'))

descripition = soup.find('meta',attrs ={"name":"descripition"})

if descripition:
  print("Descripition:")
  print(descripition.get('content'))

scripts = soup.find_all("script")
for script in scripts:
  print(script.get("src"))

og_image =soup.find("meta",attrs={"property":"og:image"})
print(og_image["content"])

og_title = soup.find("meta",property ="og:title")
print(og_title["content"])