# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfkH1_0ekG-5VIfyVo7RVwY1VSlJivRb
"""

import pandas as pd

prices = [1234, 56700 ,89034, 23456, 2345]
products = ["earpods","smartphone","laptop","smartwatch","bluetooth"]

product_prices = pd.Series(prices , index =products)
print(product_prices)

print("mean:",product_prices.mean())
print("sum:",product_prices.sum())
print("max:",product_prices.max())
print("min:",product_prices.min())

print(product_prices.head(2))
print(product_prices.tail(1))

print(product_prices.apply(lambda x : f'₹{x+(x*0.18)}'))
print(product_prices.map(lambda x: f"₹{x}.00"))

print(product_prices.sort_values())
print(product_prices.sort_index())
print(product_prices.sort_index(ascending = False))
print(product_prices.value_counts())

data ={
   "products" :[ "wireless Earbuds", "Smartphone", "laptop", "smartwatch","bluetooth"],
   "brand":["soundmax","lenova","apple","samsung","Timetrack"],
   "price":[2999, 50000,90000,2456,1345],
   "stock":[50, 40, 30, 20, 60],
   "best seller":[True,False,True,True,False]
    }

df = pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd
uploaded = files.upload()
df = pd.read_excel("python_pandas.xlsx")
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(3))
print(df.tail(10))

print(df.iloc[0])
print(df.iloc[10])

print(df['Product'])

print(df)
print(df.loc[2,"Brand"])
print(df.loc[3,"Product"])
print(df.loc[12,"Stock"])
print(df.iloc[4,0])
print(df.iloc[2,1])
print(df.iloc[3,3])

df_dropped = df.drop(columns=["Stock"])
print(df_dropped)   # df.drop(columns =["Stock"],inplace=True)

df_renamed = df.rename(columns ={"Product":"Product_name"})
print(df_renamed)  # df_rename = df.rename(columns ={"Price":"Cost"},inplace=True)

print(df)
print(df.loc[df["BestSeller"]==True])
print(df.loc[df["Stock"] <40])
print(df.loc[df["Price"]<10000])

df_grouped = df.groupby("Brand").agg({"Price":"mean", "Stock": "sum"})
print(df_grouped)

grouped = df.groupby("Brand").agg({"Price": ["mean","min", "max", "sum"]})
print(grouped)

grouped = df.groupby("Brand")["Price"].mean()
print(grouped)





data2 = {
    "Brand":["SoundMax","TechNova","ByteCore","TimeTrack","EchoBoom"],
    "Rating":[4.2, 4.5, 4.0, 4.1, 3.9],
    "Discount":[28,40,16,10,5]
}
df_ratings = pd.DataFrame(data2)
print(df_ratings)

df_merged = df.merge(df_ratings, on ="Brand")
print("Merged DataFrame(Adding Ratings) : \n" ,df_merged)

new_data = {
    "Product":["Tablet"],
    "Brand": ["Smartware"],
    "Price": [1987],
    "Stock":[25],
    "BestSeller":[True]

}
df_new = pd.DataFrame(new_data)
print(df_new)

df_concat = pd.concat([df,df_new],ignore_index=True)
print("Concatenated DataFrame:\n",df_concat)